# fly.toml app configuration file generated for unboundtest on 2023-12-07T11:16:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unbound19test"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 1232

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 1
    soft_limit = 1

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
